(
 ("~/.dotfiles/")

 ("~/.emacs.d/init.el")
 ("~/.emacs.d/straight/repos/doc-at-point.el/")
 ("~/.emacs.d/straight/repos/etmux.el/")
 ("~/.emacs.d/straight/repos/lowkey-mode-line.el/")
 ("~/.emacs.d/straight/repos/replace-at-point.el/")
 ("~/.emacs.d/straight/repos/sane-windows.el/")
 ("~/.emacs.d/straight/repos/views.el/")
 ("~/.emacs.d/lisp/today/")

 ("~/vault/git/")
 ("~/vault/knowledge-base/")
 ("~/vault/projects/clojure/microblog/")
 ("~/vault/projects/code-challenges/")
 ("~/vault/projects/java/flatlab/")
 ("~/vault/projects/python/jackup/")
 ("~/vault/projects/rust/jepa/")
 ("~/vault/blog/")
 )
