(
 ("~/.dotfiles/")
 ("~/.dotfiles/bin/usr/local/bin")

 ("~/.emacs.d/init.el")
 ("~/.emacs.d/lisp/org-extra.el")
 ("~/.emacs.d/lisp/dev-extra.el")

 ("~/.emacs.d/straight/repos/dokument.el/")
 ("~/.emacs.d/straight/repos/etmux.el/")
 ("~/.emacs.d/straight/repos/lowkey-mode-line.el/")
 ("~/.emacs.d/straight/repos/replace-at-point.el/")
 ("~/.emacs.d/straight/repos/sane-windows.el/")
 ("~/.emacs.d/straight/repos/views.el/")
 ("~/.emacs.d/straight/repos/today.el/")
 ("~/.emacs.d/straight/repos/notmuch-mojn.el/")
 ("~/.emacs.d/straight/repos/straight-ui.el/")
 ("~/.emacs.d/straight/repos/augment.el/")
 ("~/.emacs.d/straight/repos/orgflow.el/")
 ("~/.emacs.d/straight/repos/zent-theme.el/")
 ("~/.emacs.d/straight/repos/org-proplines.el/")

 ("~/vault/org/")
 ("~/vault/inbox/")
 ("~/vault/courses/")
 ("~/vault/projects/clojure/microblog/")
 ("~/vault/projects/code-challenges/")
 ("~/vault/projects/java/flatlab/")
 ("~/vault/projects/python/jackup/")
 ("~/vault/projects/python/arkiv/")
 ("~/vault/projects/rust/jepa/")
 ("~/vault/projects/rust/jelp/")
 ("~/vault/projects/rust/jeml/")
 ("~/vault/projects/cpp/jaleidoscope/")

 ("~/vault/blog/")
 )
